[versions]
agp = "8.13.0"
kotlin = "2.2.20"
android-minSdk = "24"
android-compileSdk = "36"
vanniktechMavenPublish = "0.34.0"
ksoup-ver = "0.2.5"
ktor = "3.3.3"
kotlinx-coroutines-core-ver = "1.10.2"
napier-ver = "2.7.1"
kotlinx-datetime-ver = "0.7.1"
slf4j-android-ver = "1.7.36"
logback-classic-ver = "1.5.21"

[libraries]
# commonMain
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup-ver" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup-ver" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core-ver" }
napier = { module = "io.github.aakira:napier", version.ref = "napier-ver" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime-ver" }
# commonTest
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
# androidMain & jvmMain
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
# androidMain only
slf4j-android = { module = "org.slf4j:slf4j-android", version.ref = "slf4j-android-ver" }
# jvmMain only
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-classic-ver" }
# iosMain
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
# linuxX64Main
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

[plugins]
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechMavenPublish" }